Topic/operator equal
stonneau/spline pull request #13
Opened 2019-12-06 09:11 UTC by pFernbach

This PR add the method `isApprox` and the operator `==` and `!=` to `curve_abc` and reimplement it in most of the child class. 
The operator `==` in `curve_abc` check if two generic curves are equal **by value** ie. if the evaluate and derivate method of both curves return the same value along all the curve (using discretization). 
In the child class, the operator `==` check exactly if the two curves of the same type are the same (ie. by checking the coefficients values in a polynomial or the control points in a Bezier).

This choice of implementing a generic equality test between any kind of curves was made because two curves could represent the same trajectory using two different formulations (see the unit tests).

This PR also add the python binding of the operator `==` and `!=` and unit tests in C++ and Python.

2019-12-06 22:23 UTC, stonneau requested changes
I am strongly opposed having compute_derivate returning a pointer instead of a copy, and all the subsequent pointers deletion that occur everywhere. If this is really needed somewhere then the method who actually needs this should make here own pointer of it, even if it requires two object creations (I assume this is in python?)

In any case primitives and derivatives apis should be the same.

Similarly having all the explicit cast is problematic. We need to discuss about a different hierarchy of class if those mechanisms are really needed because it means my original design is bad if it comes to this

2019-12-06 22:23 UTC, stonneau commented on include/curves/bezier_curve.h
> +      return new bezier_curve_t(*this);
Why do you need a pointer instead of a copy ? I

2019-12-06 22:23 UTC, stonneau commented on include/curves/bezier_curve.h
> +    delete deriv;
See above. I really don't like this.

2019-12-06 22:23 UTC, stonneau commented on include/curves/exact_cubic.h
> -struct exact_cubic : public piecewise_curve<Time, Numeric, Safe, Point, T_Point, SplineBase> {
Shouldn't it be CurveBase ?

2019-12-06 22:23 UTC, stonneau commented on include/curves/optimization/integral_cost.h
> +  delete acc;
No ok really I don't want this

2019-12-06 22:23 UTC, stonneau commented on include/curves/polynomial.h
> +      return new polynomial_t(*this);
same thing

2019-12-06 22:30 UTC, stonneau commented on include/curves/bezier_curve.h
> +    //std::cout<<"is approx in bezier called."<<std::endl;
cleaning

2019-12-06 22:30 UTC, stonneau commented on include/curves/cubic_hermite_spline.h
> +    //std::cout<<"is approx in hermite called."<<std::endl;
cleaning

2019-12-06 22:30 UTC, stonneau commented on include/curves/polynomial.h
> +    //std::cout<<"is approx in polynomial called."<<std::endl;
cleaning

2019-12-06 22:31 UTC, stonneau commented on include/curves/se3_curve.h
> +    //std::cout<<"is approx in SE3 called."<<std::endl;
cleaning

2019-12-06 22:31 UTC, stonneau commented on include/curves/so3_linear.h
> +    //std::cout<<"is approx in SO3 called."<<std::endl;
cleaining

2019-12-07 08:38 UTC, pFernbach commented
There have been an issue on the repo, probably due to the mirroring with gitlab, and now this PR encompass the commits of two separate PR.

Most of your comment concern the other PR. I close this one and I will open the one with the correct commits.

2019-12-07 08:38 UTC, closed without merging